//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI08_aplikacija.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Biljke
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Biljke()
        {
            this.Prod_biljke = new HashSet<Prod_biljke>();
            this.Prod_biljke1 = new HashSet<Prod_biljke>();
        }
    
        public int ID_Biljke { get; set; }
        public string Naziv { get; set; }
        public string Vrsta { get; set; }
        public string Sadnja { get; set; }
        public int Količina_zasađene { get; set; }
        public string Berba { get; set; }
        public int Količina_dobivenih_plodova { get; set; }
        public Nullable<int> ID_Zemljište { get; set; }
        public Nullable<int> id_Radnja { get; set; }
    
        public virtual Radnja Radnja { get; set; }
        public virtual Zemljište Zemljište { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prod_biljke> Prod_biljke { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prod_biljke> Prod_biljke1 { get; set; }
    }
}
