//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI08_aplikacija.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mlijekomat
    {
        public int ID_Mlijekomat { get; set; }
        public string Lokacija { get; set; }
        public string Punjenje { get; set; }
        public string Pražnjenje { get; set; }
        public double Troškovi_održavanja { get; set; }
        public double Zarada { get; set; }
        public int Kapacitet { get; set; }
        public int ID_Farma { get; set; }
    
        public virtual Farma Farma { get; set; }
    }
}
