//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI08_aplikacija.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PI08Model : DbContext
    {
        public PI08Model()
            : base("name=PI08Model")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Biljke> Biljkes { get; set; }
        public virtual DbSet<Farma> Farmas { get; set; }
        public virtual DbSet<Hrana> Hranas { get; set; }
        public virtual DbSet<Hrana_Životinja> Hrana_Životinja { get; set; }
        public virtual DbSet<Kupnja> Kupnjas { get; set; }
        public virtual DbSet<Mlijekomat> Mlijekomats { get; set; }
        public virtual DbSet<Prodaja> Prodajas { get; set; }
        public virtual DbSet<Prodaja_Životinje> Prodaja_Životinje { get; set; }
        public virtual DbSet<Prod_biljke> Prod_biljke { get; set; }
        public virtual DbSet<Rad_za_drugoga> Rad_za_drugogas { get; set; }
        public virtual DbSet<Radnja> Radnjas { get; set; }
        public virtual DbSet<Stroj> Strojs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Zemljište> Zemljište { get; set; }
        public virtual DbSet<Životinja> Životinja { get; set; }
    }
}
