//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI08_aplikacija.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rad_za_drugoga
    {
        public long id { get; set; }
        public Nullable<System.DateTime> datum_vrijeme { get; set; }
        public Nullable<double> zarada { get; set; }
        public Nullable<double> trajanje { get; set; }
        public Nullable<int> id_stroj { get; set; }
    
        public virtual Stroj Stroj { get; set; }
    }
}
