//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI08_aplikacija.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Radnja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Radnja()
        {
            this.Biljkes = new HashSet<Biljke>();
        }
    
        public int id_radnje { get; set; }
        public string naziv { get; set; }
        public decimal trosak { get; set; }
        public decimal dobit { get; set; }
        public System.DateTime pocetak_radnje { get; set; }
        public System.DateTime kraj_radnje { get; set; }
        public Nullable<int> ID_Zemljište { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Biljke> Biljkes { get; set; }
        public virtual Zemljište Zemljište { get; set; }
    }
}
