//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI08_aplikacija.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zemljište
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zemljište()
        {
            this.Biljkes = new HashSet<Biljke>();
            this.Radnjas = new HashSet<Radnja>();
        }
    
        public int ID_Zemljište { get; set; }
        public string Naziv { get; set; }
        public string Lokacija { get; set; }
        public System.DateTime Korišteno_od { get; set; }
        public System.DateTime Korišteno_do { get; set; }
        public string Pogodnost { get; set; }
        public int ID_Farma { get; set; }
        public string Vlasnik { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Biljke> Biljkes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Radnja> Radnjas { get; set; }
    }
}
