//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI08_aplikacija.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Životinja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Životinja()
        {
            this.Hrana_Životinja = new HashSet<Hrana_Životinja>();
            this.Prodaja_Životinje = new HashSet<Prodaja_Životinje>();
        }
    
        public int ID_Životinje { get; set; }
        public string Ime { get; set; }
        public string Vrsta { get; set; }
        public string Proizvodi { get; set; }
        public int Označena { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hrana_Životinja> Hrana_Životinja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prodaja_Životinje> Prodaja_Životinje { get; set; }
    }
}
